/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crp.chit.system.Control;

import crp.chit.system.Beans.admins;
import crp.chit.system.Dao.admin_dao;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author Osura
 */
public class admin_details_interface extends javax.swing.JFrame {

    private static int adminId =0;
    private static int result,a_id,row,i;
    private static String nic,name,designation,pass,password,p1;
    private static DefaultTableModel model;
    private static admins a1;
    private static Vector v1;
    /**
     * Creates new form delete_admin_interface
     */
    public admin_details_interface(int adminId) {
        initComponents();
        adminFill();
        this.adminId = adminId;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        A_Password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        A_Designation = new javax.swing.JTextField();
        A_Name = new javax.swing.JTextField();
        A_Nic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        A_Table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        A_S_Id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(699, 890));
        setResizable(false);

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-update-user-48.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-delete-bin-48.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(125, 57));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        A_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter your password    : ");

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-submit-progress-48.png"))); // NOI18N
        jButton2.setText("Submit");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        A_Designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        A_Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_DesignationActionPerformed(evt);
            }
        });

        A_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        A_Nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        A_Nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A_NicKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Enter your name         : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter your designation : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter your NIC           : ");

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter  admin details here :-");

        jPanel2.setBackground(new java.awt.Color(251, 197, 49));

        jLabel1.setBackground(new java.awt.Color(251, 197, 49));
        jLabel1.setFont(new java.awt.Font("STXihei", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Registration Form");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-return-48.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        A_Table.setBackground(new java.awt.Color(255, 255, 153));
        A_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin Id", "Nic", "Name", "Designation", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        A_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(A_Table);
        if (A_Table.getColumnModel().getColumnCount() > 0) {
            A_Table.getColumnModel().getColumn(0).setResizable(false);
            A_Table.getColumnModel().getColumn(1).setResizable(false);
            A_Table.getColumnModel().getColumn(2).setResizable(false);
            A_Table.getColumnModel().getColumn(3).setResizable(false);
            A_Table.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-search-48.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Search by id :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(A_S_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(A_S_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jButton4)
                                .addGap(31, 31, 31)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(A_Nic, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_Designation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_Nic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_Designation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Click this button to add a new admin. 
      try{
          nic = A_Nic.getText();
          name = A_Name.getText();
          designation = A_Designation.getText();
          pass = A_Password.getText();
          if(nic.length()!=0 && nic.length()==10 && (nic.endsWith("v") || nic.endsWith("V") || nic.endsWith("x") || nic.endsWith("X"))){
                if(name.length()!=0 && name.length()<=120){
                    if(designation.length()!=0 && designation.length()<=20){
                        if(pass.length()!=0){
                            //Converting the user entered password to a hash.
                             password = BCrypt.hashpw(pass,BCrypt.gensalt(12));
                            //Inserting an admin to the database.
                            a1 = new admins();
                            a1.setNic(nic);
                            a1.setName(name);
                            a1.setDesignation(designation);
                            a1.setPassword(password);
                            i = admin_dao.addAdmin(a1);
                            //Check if the add function is returning a true/false value and display relavant information for the user.
                            if(i==1){
                                    JOptionPane.showMessageDialog(null, "Admin added successfully","System",JOptionPane.INFORMATION_MESSAGE);
                                    admin_details_interface a2 = new admin_details_interface(adminId);
                                    a2.setVisible(true);
                                    dispose();

                             }else{
                                    JOptionPane.showMessageDialog(null, "Failed to add admin","System",JOptionPane.ERROR_MESSAGE);
                                    A_Nic.setText("");
                                    A_Name.setText("");
                                    A_Designation.setText("");
                                    A_Password.setText("");
                                }
                        }else{
                            JOptionPane.showMessageDialog(null, "Please enter valid password.","System",JOptionPane.ERROR_MESSAGE);
                            A_Nic.setText("");
                            A_Name.setText("");
                            A_Designation.setText("");
                            A_Password.setText("");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter a valid designation.","System",JOptionPane.ERROR_MESSAGE);
                        A_Nic.setText("");
                        A_Name.setText("");
                        A_Designation.setText("");
                        A_Password.setText("");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter a valid name.","System",JOptionPane.ERROR_MESSAGE);
                    A_Nic.setText("");
                    A_Name.setText("");
                    A_Designation.setText("");
                    A_Password.setText("");
                }
              
          }else{
              JOptionPane.showMessageDialog(null, "Please enter a valid NIC.","System",JOptionPane.ERROR_MESSAGE);
              A_Nic.setText("");
              A_Name.setText("");
              A_Designation.setText("");
              A_Password.setText("");
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Please fill all the information correctly.","System",JOptionPane.ERROR_MESSAGE);
          e.printStackTrace();
          
      }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // pressing this to go back to home page.
        home_page home = new home_page(adminId);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        //Click this button to delete the selected row value from database.
        row = A_Table.getSelectedRow();
        a_id = Integer.valueOf(A_Table.getValueAt(row, 0).toString());
        result = admin_dao.deleteAdmin(a_id);
        //if the result is true/false display relavant message to the user.
        if(result>0){
            JOptionPane.showMessageDialog(null, "Deleted successfully.","System",JOptionPane.INFORMATION_MESSAGE);
            admin_details_interface a1 = new admin_details_interface(adminId);
            a1.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Delete failed.","System",JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select a row.","System",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Click here to update information about admin. 
        try{
            row = A_Table.getSelectedRow();
            a_id = Integer.valueOf(A_Table.getValueAt(row, 0).toString());
            nic = A_Table.getValueAt(row, 1).toString();
            name = A_Table.getValueAt(row, 2).toString();
            designation = A_Table.getValueAt(row, 3).toString();
            pass = A_Table.getValueAt(row, 4).toString();
             if(nic.length()!=0 && nic.length()==10 && (nic.endsWith("v") || nic.endsWith("V") || nic.endsWith("x") || nic.endsWith("X") )){
                if(name.length()!=0 && name.length()<=120){
                    if(designation.length()!=0 && designation.length()<=20){
                        if(pass.length()!=0){
                                    v1 = admin_dao.searchAdmin(a_id);
                                    System.out.println(v1.get(4));
                                    if(pass.equals(v1.get(4))){
                                        a1 = new admins();
                                        a1.setNic(nic);
                                        a1.setName(name);
                                        a1.setDesignation(designation);
                                        result = admin_dao.updateAdminWithoutPass(a1, a_id);
                                        //if the result is true/false display relavant information to the user.
                                        if(result==1){
                                            JOptionPane.showMessageDialog(null, "Successfully updated.","System",JOptionPane.INFORMATION_MESSAGE);
                                            admin_details_interface a2 = new admin_details_interface(adminId);
                                            a2.setVisible(true);
                                            dispose();
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Failed to update.","System",JOptionPane.ERROR_MESSAGE);
                                        }
                                    }else{
                                        a1 = new admins();
                                        a1.setNic(nic);
                                        a1.setName(name);
                                        a1.setDesignation(designation);
                                        password = BCrypt.hashpw(pass, BCrypt.gensalt(12));
                                        a1.setPassword(password);
                                        result = admin_dao.updateAdmin(a1, a_id);
                                        //if the result is true/false display relavant information to the user.
                                        if(result==1){
                                            JOptionPane.showMessageDialog(null, "Successfully updated.","System",JOptionPane.INFORMATION_MESSAGE);
                                            admin_details_interface a2 = new admin_details_interface(adminId);
                                            a2.setVisible(true);
                                            dispose();
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Failed to update.","System",JOptionPane.ERROR_MESSAGE);
                                        }
                                    } 
                        }else{
                            JOptionPane.showMessageDialog(null, "Please enter valid password.","System",JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter a valid designation.","System",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter a valid name.","System",JOptionPane.ERROR_MESSAGE);
                }
              
          }else{
              JOptionPane.showMessageDialog(null, "Please enter a valid NIC.","System",JOptionPane.ERROR_MESSAGE);
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select a row.","System",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void A_DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_DesignationActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Click here to search for admin by id.
        try{
            //Check if the user entered a value or left as blank.
            if(A_S_Id.getText().length()!=0 && A_S_Id.getText().length()<=10){
               a_id = Integer.parseInt(A_S_Id.getText());
               //Check if that integer is between these values.
                         v1 = admin_dao.searchAdmin(a_id);
                         //Check the vector value and display relavant information to the user.
                         System.out.println(v1);
                        if(v1==null){
                         JOptionPane.showMessageDialog(null, "Please enter a valid id.","System",JOptionPane.ERROR_MESSAGE);
                        A_S_Id.setText("");
                        }else{
                            
                            A_Table.setModel(new DefaultTableModel(null,new String[]{"Admin Id","NIC","Name","Designation","Password"}));
                            model = (DefaultTableModel) A_Table.getModel();
                            model.addRow(v1);
                        }
            }else{
                JOptionPane.showMessageDialog(null, "Please enter an id.","System",JOptionPane.ERROR_MESSAGE);
                A_S_Id.setText("");
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a numeric value.","System",JOptionPane.ERROR_MESSAGE);
            A_S_Id.setText("");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void A_NicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_NicKeyPressed

    }//GEN-LAST:event_A_NicKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_details_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_details_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_details_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_details_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_details_interface(adminId).setVisible(true);
            }
        });
    }
    
    //Call this method in the constructor to get all the existing admins from the database and fill them in the jTable.
    public void adminFill(){
        v1 = admin_dao.getAdmins();
        model = (DefaultTableModel) A_Table.getModel();
        if(v1==null){
            
        }else{
            for(int i = 0; i<v1.size(); i++){
            model.addRow((Vector) v1.get(i));
            } 
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A_Designation;
    private javax.swing.JTextField A_Name;
    private javax.swing.JTextField A_Nic;
    private javax.swing.JPasswordField A_Password;
    private javax.swing.JTextField A_S_Id;
    private javax.swing.JTable A_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
