/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crp.chit.system.Control;

import crp.chit.system.Beans.visitors;
import crp.chit.system.Beans.visits;
import crp.chit.system.Dao.visitors_dao;
import crp.chit.system.Dao.visits_dao;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Osura
 */
public class chit_interface extends javax.swing.JFrame {

    private static int result,result1,contact,p_id;
    private static String nic,name,address,relation,place;
    private static Vector visitor;
    private static visitors v2;
    private static visits v1;
    
    /**
     * Creates new form chit_interface
     */
    public chit_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        V_Prisoner_Place = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        V_Prisoner_Id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        V_Name = new javax.swing.JTextField();
        V_Contact = new javax.swing.JTextField();
        V_Nic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        V_Address = new javax.swing.JTextField();
        V_Relation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        V_Prisoner_Place.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRP", "Hospital", "Magazine" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Enter your relationship to prisoner : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Enter your contact NO                 : ");

        V_Prisoner_Id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_Prisoner_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_Prisoner_IdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Enter prisoner's current place       :");

        V_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_NameActionPerformed(evt);
            }
        });

        V_Contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        V_Nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Enter prisoner id                        : ");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-submit-progress-48.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        V_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        V_Relation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Enter your Name                         :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Enter your NIC                           : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Enter your Address                      : ");

        jPanel2.setBackground(new java.awt.Color(251, 197, 49));

        jLabel2.setFont(new java.awt.Font("STXihei", 2, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome!");

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-return-48.png"))); // NOI18N
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(V_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(V_Nic)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(V_Prisoner_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addComponent(V_Prisoner_Id)
                            .addComponent(V_Relation)
                            .addComponent(V_Contact, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(V_Address, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(247, 247, 247))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(399, 399, 399))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(V_Nic, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(V_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(V_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(V_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(V_Relation, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(V_Prisoner_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(V_Prisoner_Place)))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("c_submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void V_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_NameActionPerformed

    private void V_Prisoner_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_Prisoner_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_Prisoner_IdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           nic = V_Nic.getText();
           name = V_Name.getText();
           address = V_Address.getText();
           contact = Integer.parseInt(V_Contact.getText());
           relation = V_Relation.getText();
           p_id = Integer.parseInt(V_Prisoner_Id.getText());
           place = V_Prisoner_Place.getSelectedItem().toString();
           if(nic.length()!=0 && nic.length()==10 &&(nic.endsWith("v") || nic.endsWith("x") || nic.endsWith("V") || nic.endsWith("X"))){
               if(name.length()!=0 && name.length()<=120){
                   if(address.length()!=0 && address.length()<=120){
                       if(V_Contact.getText().length()!=0 && V_Contact.getText().length()==10 && (V_Contact.getText().startsWith(String.valueOf("07")))){
                           if(relation.length()!=0 && relation.length()<=20){
                               if(V_Prisoner_Id.getText().length()!=0 && V_Prisoner_Id.getText().length()<=10){
                                   if(place!=null){
                                        //Check if a visitor exists under the current NIC.
                                        visitor = visitors_dao.serchVisitorByNic(nic);
                                        if(visitor==null){
                                            //Check if a prisoner exists undeer the current id.
                                             //If a user doesn't exist under the current NIC insert the user and the visit both.

                                            //Insert the visitor first to avoid foreignkey constraint errors.
                                            v2 = new visitors();
                                            v2.setNic(nic);
                                            v2.setName(name);
                                            v2.setAddress(address);
                                            v2.setContact(contact);
                                            result = visitors_dao.addVisitor(v2);

                                            visitor = visitors_dao.serchVisitorByNic(nic);
                                            //Insert the visit.
                                            v1 = new visits();
                                            v1.setTime(Time.valueOf(LocalTime.now()));
                                            v1.setDate(Date.valueOf(LocalDate.now()));
                                            v1.setPlace(place);
                                            v1.setRelation(relation);
                                            v1.setPrisoner_id(p_id);
                                            v1.setV_Id(Integer.valueOf(visitor.get(0).toString()));
                                            result1 = visits_dao.addVisit(v1);
                                            //Check if the add function is returning a true/false value and display relavant information for the user.
                                            if(result==1){
                                                if(result1==1){
                                                    JOptionPane.showMessageDialog(null, "Chit added successfully.","System",JOptionPane.INFORMATION_MESSAGE);
                                                    V_Relation.setText("");
                                                    V_Prisoner_Id.setText("");
                                                    V_Nic.setText("");
                                                    V_Address.setText("");
                                                    V_Contact.setText("");
                                                    V_Name.setText("");
                                                }else{
                                                    JOptionPane.showMessageDialog(null, "Failed to add the chit.","System",JOptionPane.ERROR_MESSAGE);
                                                    V_Relation.setText("");
                                                    V_Prisoner_Id.setText("");
                                                    V_Nic.setText("");
                                                    V_Address.setText("");
                                                    V_Contact.setText("");
                                                    V_Name.setText("");
                                                }
                                            }else{
                                                JOptionPane.showMessageDialog(null, "Failed to add the chit.","System",JOptionPane.ERROR_MESSAGE);
                                                V_Relation.setText("");
                                                V_Prisoner_Id.setText("");
                                                V_Nic.setText("");
                                                V_Address.setText("");
                                                V_Contact.setText("");
                                                V_Name.setText("");
                                            }

                                        }else{

                                            //If a visitor exists insert the visit to the database.
                                            v1 = new visits();
                                            v1.setTime(Time.valueOf(LocalTime.now()));
                                            v1.setDate(Date.valueOf(LocalDate.now()));
                                            v1.setPlace(place);
                                            v1.setRelation(relation);
                                            v1.setPrisoner_id(p_id);
                                            v1.setV_Id(Integer.valueOf(visitor.get(0).toString()));
                                            result = visits_dao.addVisit(v1);

                                            if(result==1){
                                                JOptionPane.showMessageDialog(null, "Chit added successfully.","System",JOptionPane.INFORMATION_MESSAGE);
                                                V_Relation.setText("");
                                                V_Prisoner_Id.setText("");
                                                V_Nic.setText("");
                                                V_Address.setText("");
                                                V_Contact.setText("");
                                                V_Name.setText("");

                                            }else{
                                                JOptionPane.showMessageDialog(null, "Failed to add the chit.","System",JOptionPane.ERROR_MESSAGE);
                                                V_Relation.setText("");
                                                V_Prisoner_Id.setText("");
                                                V_Nic.setText("");
                                                V_Address.setText("");
                                                V_Contact.setText("");
                                                V_Name.setText("");
                                            }

                                        }
                                   }else{
                                        JOptionPane.showMessageDialog(null, "Please select the place of the visit.","System",JOptionPane.ERROR_MESSAGE);
                                   }
                               }else{
                                    JOptionPane.showMessageDialog(null, "Please enter a valid prisoner id.","System",JOptionPane.ERROR_MESSAGE);
                                    V_Prisoner_Id.setText("");
                               }
                           }else{
                                JOptionPane.showMessageDialog(null, "Please enter a valid relationship.","System",JOptionPane.ERROR_MESSAGE);
                                V_Relation.setText("");
                           }
                       }else{
                            JOptionPane.showMessageDialog(null, "Please enter a valid contact number.","System",JOptionPane.ERROR_MESSAGE);
                            V_Contact.setText("");
                       }
                   }else{
                       JOptionPane.showMessageDialog(null, "Please enter a valid address.","System",JOptionPane.ERROR_MESSAGE);
                        V_Address.setText("");
                   }
               }else{
                    JOptionPane.showMessageDialog(null, "Please enter a valid name.","System",JOptionPane.ERROR_MESSAGE);
                    V_Name.setText("");
               }
           }else{
                JOptionPane.showMessageDialog(null, "Please enter a valid NIC.","System",JOptionPane.ERROR_MESSAGE);
                V_Nic.setText("");
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Please fill all the information correctly.","System",JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Press this to go back to chit interface.
        startup s1 = new startup();
        s1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chit_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chit_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chit_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chit_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chit_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField V_Address;
    private javax.swing.JTextField V_Contact;
    private javax.swing.JTextField V_Name;
    private javax.swing.JTextField V_Nic;
    private javax.swing.JTextField V_Prisoner_Id;
    private javax.swing.JComboBox<String> V_Prisoner_Place;
    private javax.swing.JTextField V_Relation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
