/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crp.chit.system.Control;

import crp.chit.system.Beans.prisoners;
import crp.chit.system.Dao.courts_dao;
import crp.chit.system.Dao.prisoner_dao;
import static crp.chit.system.Dao.send_mail.send;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osura
 */
public class prisoner_interface extends javax.swing.JFrame {

    private static int adminId = 0;
    private static int result,p_id,row;
    private static DefaultTableModel model;
    private static String to,sub,message,user,pass;
    private static prisoners p1;
    private static Vector v1;
    private static String nic,name,cell,email,place;
    private static int phone,c_id;
    /**
     * Creates new form prisoner_interface
     */
    public prisoner_interface(int adminId) {
        initComponents();
        comboBoxFill();
        prisonerFill();
        this.adminId = adminId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        P_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        P_Nic = new javax.swing.JTextField();
        P_Name = new javax.swing.JTextField();
        P_Cell_No = new javax.swing.JTextField();
        P_R_Phone_No = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        P_Courts_List = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        P_R_Email = new javax.swing.JTextField();
        P_Place = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        P_S_Id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        P_Table.setBackground(new java.awt.Color(255, 255, 153));
        P_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prisoner_id", "Prisoner_Nic", "Name", "Cell_No", "Place", "Relations Phone No", "Relation email address", "Court_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        P_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(P_Table);
        if (P_Table.getColumnModel().getColumnCount() > 0) {
            P_Table.getColumnModel().getColumn(0).setResizable(false);
            P_Table.getColumnModel().getColumn(1).setResizable(false);
            P_Table.getColumnModel().getColumn(2).setResizable(false);
            P_Table.getColumnModel().getColumn(3).setResizable(false);
            P_Table.getColumnModel().getColumn(4).setResizable(false);
            P_Table.getColumnModel().getColumn(5).setResizable(false);
            P_Table.getColumnModel().getColumn(5).setPreferredWidth(120);
            P_Table.getColumnModel().getColumn(6).setResizable(false);
            P_Table.getColumnModel().getColumn(6).setPreferredWidth(130);
            P_Table.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter prisoner's NIC                       : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter prisoner's name                     : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter prisoner's Cell NO                  : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter prisoner's relation's phone NO  : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Enter prisoner's place                     : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Assign prisoners court                    :");

        P_Nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P_Nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_NicActionPerformed(evt);
            }
        });

        P_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        P_Cell_No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        P_R_Phone_No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-submit-progress-48.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        P_Courts_List.setMaximumRowCount(30);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-delete-bin-48.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-update-user-48.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Enter prisoner's relation's E-mail       : ");

        P_R_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        P_Place.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRP", "Hospital", "Magazine" }));

        jPanel2.setBackground(new java.awt.Color(251, 197, 49));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-return-48.png"))); // NOI18N
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("STXihei", 0, 36)); // NOI18N
        jLabel8.setText("Prisoner Registration Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addGap(197, 197, 197)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Enter prisoner details :-");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-search-48.png"))); // NOI18N
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        P_S_Id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Search by id :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(P_S_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(P_S_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(P_Place, 0, 527, Short.MAX_VALUE)
                                            .addComponent(P_R_Email)
                                            .addComponent(P_Name)
                                            .addComponent(P_Cell_No)
                                            .addComponent(P_Nic)
                                            .addComponent(P_R_Phone_No)
                                            .addComponent(P_Courts_List, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(435, 435, 435)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(237, 237, 237))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jButton5)
                                .addGap(50, 50, 50)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(P_Nic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_Cell_No, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_R_Phone_No, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_R_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_Place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_Courts_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void P_NicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_NicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_NicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Click here to insert a prisoner to the database.
        try{
            //Getting user inputs from the GUI and saving them in a prisoner object.
            nic = P_Nic.getText();
            name = P_Name.getText();
            cell = P_Cell_No.getText();
            phone = Integer.parseInt(P_R_Phone_No.getText());
            email = P_R_Email.getText();
            place = P_Place.getSelectedItem().toString();
            c_id = Integer.parseInt(P_Courts_List.getSelectedItem().toString());
            if(nic.length()!=0 && nic.length()==10 && (nic.endsWith("v") || nic.endsWith("V") || nic.endsWith("x") || nic.endsWith("X"))){
                if(name.length()!=0 && name.length()<=120){
                    if(cell.length()!=0 && cell.length()<=10){
                        if(P_R_Phone_No.getText().length()!=0 && P_R_Phone_No.getText().length()==10){
                            if(email.length()!=0 && email.length()<=120){
                               if(place!= null){
                                  if(c_id!=0){
                                        p1 = new prisoners();
                                        p1.setNic(nic);
                                        p1.setName(name);
                                        p1.setCell_no(cell);
                                        p1.setR_Phone(phone);
                                        p1.setEmail(email);
                                        p1.setPlace(place);
                                        p1.setCourt_id(c_id);
                                        // Adding the prisoner to the database.
                                        result = prisoner_dao.addPrisoner(p1);
                                        //if the result is true/false showing the user relavant output.
                                        if(result==1){
                                            JOptionPane.showMessageDialog(null, "Prisoner added successfully.","System",JOptionPane.INFORMATION_MESSAGE);
                                            to = P_R_Email.getText();
                                            sub = "About imprisonment";
                                            message = "Please take note that the following person named "+P_Name.getText()+" has been imprisoned in the Colombo Remand Prison section "+P_Place.getSelectedItem().toString()+".";
                                            user = "prisonchitsystem@gmail.com";
                                            pass = "123!@#qweQWE";
                                            send(to,sub,message,user,pass);
                                            prisoner_interface p2 = new prisoner_interface(adminId);
                                            p2.setVisible(true);
                                            dispose();
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Failed to add the prisoner.","System",JOptionPane.ERROR_MESSAGE);
                                            P_Nic.setText("");
                                            P_Name.setText("");
                                            P_Cell_No.setText("");
                                            P_R_Phone_No.setText("");
                                            P_R_Email.setText("");
                                        } 
                                  }else{
                                        JOptionPane.showMessageDialog(null, "Please select court id.","System",JOptionPane.ERROR_MESSAGE);
                                  } 
                               }else{
                                   JOptionPane.showMessageDialog(null, "Please select prisoner's place.","System",JOptionPane.ERROR_MESSAGE);
                               }
                            }else{
                                JOptionPane.showMessageDialog(null, "Please enter valid email.","System",JOptionPane.ERROR_MESSAGE);
                                P_R_Email.setText("");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Please enter valid phone number.","System",JOptionPane.ERROR_MESSAGE);
                            P_R_Phone_No.setText("");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter valid cell number.","System",JOptionPane.ERROR_MESSAGE);
                        P_Cell_No.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter valid name.","System",JOptionPane.ERROR_MESSAGE);
                    P_Name.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please enter valid NIC.","System",JOptionPane.ERROR_MESSAGE);
                P_Nic.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please fill all the information correctly.","System",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Press this to go back to home page
        home_page home = new home_page(adminId);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            // TODO add your handling code here:
        //Click here to delete a prisoner from the database.
        row = P_Table.getSelectedRow();
        p_id = Integer.valueOf(P_Table.getValueAt(row, 0).toString());
        result = prisoner_dao.deletePrisoner(p_id);
        //if the result is true/false display the relavant information to the user.
        if(result==1){
            JOptionPane.showMessageDialog(null, "Prisoner deleted successfully.","System",JOptionPane.INFORMATION_MESSAGE);
            prisoner_interface p2 = new prisoner_interface(adminId);
            p2.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Failed to delete.","System",JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select a row.","System",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Click here to update data about prisoners.
        try{
        //Getting user updates and updating the prisoner details.
            row = P_Table.getSelectedRow();
            p_id = Integer.valueOf(P_Table.getValueAt(row, 0).toString());
            nic = P_Table.getValueAt(row, 1).toString();
            name = P_Table.getValueAt(row, 2).toString();
            cell = P_Table.getValueAt(row, 3).toString();
            phone = Integer.parseInt(P_Table.getValueAt(row, 5).toString());
            email = P_Table.getValueAt(row, 6).toString();
            place = P_Table.getValueAt(row, 4).toString();
            c_id = Integer.parseInt(P_Table.getValueAt(row, 7).toString());
            if(nic.length()!=0 && nic.length()==10 && (nic.endsWith("v") || nic.endsWith("V") || nic.endsWith("x") || nic.endsWith("X"))){
                if(name.length()!=0 && name.length()<=120){
                    if(cell.length()!=0 && cell.length()<=10){
                        if(P_Table.getValueAt(row, 5).toString().length()!=0 && P_Table.getValueAt(row, 5).toString().length()==10){
                            if(email.length()!=0 && email.length()<=120){
                               if(place!= null){
                                  if(P_Table.getValueAt(row, 7).toString().length()!=0 && P_Table.getValueAt(row, 7).toString().length()==10){    
                                    p1 = new prisoners();
                                    p1.setNic(nic);
                                    p1.setName(name);
                                    p1.setCell_no(cell);
                                    p1.setPlace(place);
                                    p1.setR_Phone(phone);
                                    p1.setEmail(email);
                                    p1.setCourt_id(c_id);
                                    result = prisoner_dao.updatePrisoner(p1, p_id);
                                    //if the result is true/false display relavant information to the user.
                                    if(result==1){
                                        JOptionPane.showMessageDialog(null, "Prisoner updated successfully.","System",JOptionPane.INFORMATION_MESSAGE);
                                        prisoner_interface p2 = new prisoner_interface(adminId);
                                        p2.setVisible(true);
                                        dispose();
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Failed to update the data.","System",JOptionPane.ERROR_MESSAGE);
                                    } 
                                  }else{
                                        JOptionPane.showMessageDialog(null, "Please select court id.","System",JOptionPane.ERROR_MESSAGE);
                                  } 
                               }else{
                                   JOptionPane.showMessageDialog(null, "Please select prisoner's place.","System",JOptionPane.ERROR_MESSAGE);
                               }
                            }else{
                                JOptionPane.showMessageDialog(null, "Please enter valid email.","System",JOptionPane.ERROR_MESSAGE);
                                P_R_Email.setText("");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Please enter valid phone number.","System",JOptionPane.ERROR_MESSAGE);
                            P_R_Phone_No.setText("");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter valid cell number.","System",JOptionPane.ERROR_MESSAGE);
                        P_Cell_No.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter valid name.","System",JOptionPane.ERROR_MESSAGE);
                    P_Name.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please enter valid NIC.","System",JOptionPane.ERROR_MESSAGE);
                P_Nic.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select a row.","System",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Click here to search for a prisoner by id.
        try{
            if(P_S_Id.getText().length()!=0 && P_S_Id.getText().length()<=10){
                p_id = Integer.parseInt(P_S_Id.getText());
                v1 = prisoner_dao.serchPrisoner(p_id);
                if(v1==null){
                    JOptionPane.showMessageDialog(null, "Please enter valid id.","System",JOptionPane.ERROR_MESSAGE);
                }else{
                    P_Table.setModel(new DefaultTableModel(null,new String[]{"Prisoner Id","Prisoner NIC","Name","Cell No","Place","Relations Phone No","Relations Email Address","Court Id"}));
                    model = (DefaultTableModel) P_Table.getModel();
                    model.addRow(v1);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please enter a valid id.","System",JOptionPane.ERROR_MESSAGE);
                P_S_Id.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please eneter a numeric value.","System",JOptionPane.ERROR_MESSAGE);
            P_S_Id.setText("");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prisoner_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prisoner_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prisoner_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prisoner_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prisoner_interface(adminId).setVisible(true);               
            }
        });
    }
    //Get all the court id's and fill them in the combo box.
    public void comboBoxFill(){
        //Get the existing courts from database and display their id's in the combo box.
        v1 = courts_dao.getCourtIds();
        for(int i =0; i<v1.size();i++){
           P_Courts_List.addItem(v1.get(i).toString());     
     }
    }
    //Get all the prisoners and show them in the jTable.
    public void prisonerFill(){
        //Getting all the prisoner details from database and displaying them on the jTable.
        v1 = prisoner_dao.getPrisoners();
        model = (DefaultTableModel) P_Table.getModel();
        if(v1==null){
            
        }else{
            for(int i = 0; i<v1.size();i++){
            model.addRow((Vector) v1.get(i));
            }   
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_Cell_No;
    private javax.swing.JComboBox<String> P_Courts_List;
    private javax.swing.JTextField P_Name;
    private javax.swing.JTextField P_Nic;
    private javax.swing.JComboBox<String> P_Place;
    private javax.swing.JTextField P_R_Email;
    private javax.swing.JTextField P_R_Phone_No;
    private javax.swing.JTextField P_S_Id;
    private javax.swing.JTable P_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
